version: '3.8'
services:
  database:
    image: postgres:10.3
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - DATABASE_URL='postgres://postgres:root@localhost:5432/cross-sourcerer?schema=public'
      - ENVIRONMENT=PRODUCTION
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  server:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    env_file: ../.env
    depends_on:
      - database
    networks:
      - default
    ports:
      - '8080:8080'
volumes:
  postgres:
